"""create proveedores and migrate compras.proveedor

Revision ID: 06348337ff00
Revises: 526bd222a0c7
Create Date: 2026-08-03 21:24:07.112010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06348337ff00'
down_revision: Union[str, Sequence[str], None] = '526bd222a0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('clabe', sa.String(length=18), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=True)
    # nota: NO tocar 'ix_caja_sesiones_una_abierta' (ver migración 6c2f1f71c2ed)
    op.add_column('compras', sa.Column('proveedor_id', sa.Integer(), nullable=True))

    # backfill: un Proveedor real por cada nombre distinto ya usado como texto libre
    op.execute(
        """
        INSERT INTO proveedores (nombre, activo, created_at)
        SELECT DISTINCT proveedor, true, now() FROM compras
        """
    )
    op.execute(
        """
        UPDATE compras
        SET proveedor_id = proveedores.id
        FROM proveedores
        WHERE compras.proveedor = proveedores.nombre
        """
    )

    op.alter_column('compras', 'proveedor_id', nullable=False)
    op.create_foreign_key(None, 'compras', 'proveedores', ['proveedor_id'], ['id'])
    op.drop_column('compras', 'proveedor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # nota: recrea la columna vacía; el texto libre original no se puede reconstruir a partir
    # del proveedor_id sin asumir que el nombre del Proveedor es idéntico al string histórico
    op.add_column('compras', sa.Column('proveedor', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.execute(
        """
        UPDATE compras
        SET proveedor = proveedores.nombre
        FROM proveedores
        WHERE compras.proveedor_id = proveedores.id
        """
    )
    op.alter_column('compras', 'proveedor', nullable=False)
    op.drop_constraint(None, 'compras', type_='foreignkey')
    op.drop_column('compras', 'proveedor_id')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_table('proveedores')
    # ### end Alembic commands ###
