"""create reglas_reorden and ordenes_reorden

Revision ID: 3abc139a437a
Revises: 06348337ff00
Create Date: 2026-08-03 21:30:10.520544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3abc139a437a'
down_revision: Union[str, Sequence[str], None] = '06348337ff00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglas_reorden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('umbral_stock', sa.Integer(), nullable=False),
    sa.Column('cantidad_pedido', sa.Integer(), nullable=False),
    sa.Column('costo_unitario_estimado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id')
    )
    op.create_table('ordenes_reorden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regla_reorden_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('monto_estimado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADA', 'RECHAZADA', 'PAGADA', 'ERROR', name='estado_orden_reorden'), nullable=False),
    sa.Column('aprobado_por_id', sa.Integer(), nullable=True),
    sa.Column('aprobado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('openpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['regla_reorden_id'], ['reglas_reorden.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # nota: NO tocar 'ix_caja_sesiones_una_abierta' (ver migración 6c2f1f71c2ed)
    # idempotencia (§4.6): a lo sumo una orden PENDIENTE por regla, evita duplicados por
    # reintento o doble lectura de stock concurrente
    op.create_index(
        'ix_ordenes_reorden_una_pendiente_por_regla',
        'ordenes_reorden',
        ['regla_reorden_id'],
        unique=True,
        postgresql_where=sa.text("estado = 'PENDIENTE'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ordenes_reorden_una_pendiente_por_regla', table_name='ordenes_reorden')
    op.drop_table('ordenes_reorden')
    op.drop_table('reglas_reorden')
    # ### end Alembic commands ###
