"""create categorias table and link productos

Revision ID: 3ea3b4d6b0df
Revises: bc849bc5a002
Create Date: 2026-07-25 21:57:01.303730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea3b4d6b0df'
down_revision: Union[str, Sequence[str], None] = 'bc849bc5a002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=True)
    op.add_column('productos', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'productos', 'categorias', ['categoria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_column('productos', 'categoria_id')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
