"""add configuracion_negocio and puede_retirar_excedente

Revision ID: 526bd222a0c7
Revises: 6c2f1f71c2ed
Create Date: 2026-08-03 21:15:44.029433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526bd222a0c7'
down_revision: Union[str, Sequence[str], None] = '6c2f1f71c2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_negocio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('limite_efectivo_caja', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('openpay_tope_por_orden', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('openpay_tope_diario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # fila única, sin límites configurados por defecto: el admin los define desde la UI
    op.execute("INSERT INTO configuracion_negocio (id) VALUES (1)")
    # nota: NO tocar 'ix_caja_sesiones_una_abierta' (ver migración 6c2f1f71c2ed)
    # backfill: usuarios existentes no pueden retirar excedente hasta que el admin lo habilite
    op.add_column('usuarios', sa.Column('puede_retirar_excedente', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('usuarios', 'puede_retirar_excedente', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'puede_retirar_excedente')
    op.drop_table('configuracion_negocio')
    # ### end Alembic commands ###
