"""add usuario_id to movimientos_caja and create auditoria

Revision ID: 6c2f1f71c2ed
Revises: b2c3d4e5f6a7
Create Date: 2026-08-03 21:09:29.642304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2f1f71c2ed'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=64), nullable=False),
    sa.Column('entidad', sa.String(length=64), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # nota: NO tocar el índice único parcial 'ix_caja_sesiones_una_abierta' (creado a mano en
    # a1b2c3d4e5f6, no modelado en SQLAlchemy) — autogenerate lo detecta como "removido" por error.
    op.add_column('movimientos_caja', sa.Column('usuario_id', sa.Integer(), nullable=True))
    # backfill: el actor real de movimientos históricos no quedó registrado; se asume el
    # cajero dueño de la sesión de caja (negocio de una sola caja, un cajero a la vez)
    op.execute(
        """
        UPDATE movimientos_caja
        SET usuario_id = caja_sesiones.usuario_id
        FROM caja_sesiones
        WHERE movimientos_caja.caja_id = caja_sesiones.id
        """
    )
    op.alter_column('movimientos_caja', 'usuario_id', nullable=False)
    op.create_foreign_key(None, 'movimientos_caja', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimientos_caja', type_='foreignkey')
    op.drop_column('movimientos_caja', 'usuario_id')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
