"""add forma_pago to ventas

Revision ID: e50b52925a4a
Revises: 3abc139a437a
Create Date: 2026-08-03 21:41:01.084907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e50b52925a4a'
down_revision: Union[str, Sequence[str], None] = '3abc139a437a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

forma_pago = sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', name='forma_pago')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # nota: NO tocar 'ix_caja_sesiones_una_abierta' ni 'ix_ordenes_reorden_una_pendiente_por_regla'
    # (índices únicos parciales no modelados en SQLAlchemy, ver 6c2f1f71c2ed y 3abc139a437a)
    # backfill: ventas históricas se asumen efectivo, único método existente hasta esta migración
    forma_pago.create(op.get_bind(), checkfirst=True)
    op.add_column('ventas', sa.Column('forma_pago', forma_pago, nullable=False, server_default='EFECTIVO'))
    op.alter_column('ventas', 'forma_pago', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'forma_pago')
    forma_pago.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
